# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20161012_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name=b'died'),
        ),
    ]
